"""
Deploy optimized Snowflake Stored Procedures (SQL Scripting + Recursive CTE):
  1. SF_SP_GENERATE_TRF_IN_PLAN  — single/filtered TRF generation
  2. SF_SP_RUN_ALL_PLANS         — bulk: TRUNCATE + TRF + PP

Replaces 104-UPDATE JavaScript loop with ONE recursive CTE query.
"""
import snowflake.connector, sys

WK = ",".join([f"WK_{i}" for i in range(1, 49)])

conn = snowflake.connector.connect(
    account='iafphkw-hh80816', user='akashv2kart', password='SVXqEe5pDdamMb9',
    database='V2RETAIL', schema='GOLD', warehouse='V2_WH'
)
cur = conn.cursor()

# ================================================================
# SP 1: SF_SP_GENERATE_TRF_IN_PLAN  (SQL Scripting + Recursive CTE)
# ================================================================
sp_trf_sql = f"""
CREATE OR REPLACE PROCEDURE SF_SP_GENERATE_TRF_IN_PLAN(
    START_WEEK_ID FLOAT, END_WEEK_ID FLOAT,
    STORE_CODE VARCHAR DEFAULT NULL, MAJ_CAT_PARAM VARCHAR DEFAULT NULL,
    COVER_DAYS_CM1 FLOAT DEFAULT 14, COVER_DAYS_CM2 FLOAT DEFAULT 0
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS CALLER
AS
DECLARE
    v_rows INTEGER;
    v_ts   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
BEGIN
    -- ═══ STEP 1: Week range with sequence ═══
    CREATE OR REPLACE TEMPORARY TABLE TMP_W AS
    SELECT WEEK_ID, WEEK_SEQ, FY_WEEK, FY_YEAR, WK_ST_DT, WK_END_DT,
        'WK_' || CAST(FY_WEEK AS VARCHAR) AS WK_COL,
        ROW_NUMBER() OVER (ORDER BY WEEK_ID) AS SEQ
    FROM WEEK_CALENDAR
    WHERE WEEK_ID BETWEEN :START_WEEK_ID AND :END_WEEK_ID;

    -- ═══ STEP 2: Store x Category combos ═══
    CREATE OR REPLACE TEMPORARY TABLE TMP_SC AS
    SELECT SM.ST_CD, SM.ST_NM, SM.RDC_CD, SM.RDC_NM, SM.HUB_CD, SM.HUB_NM, SM.AREA,
        BC.MAJ_CAT, BC.BIN_CAP,
        NVL(BM.SEG,'NA') AS SEG, NVL(BM.DIV,'NA') AS DIV,
        NVL(BM.SUB_DIV,'NA') AS SUB_DIV, NVL(BM.MAJ_CAT_NM,'NA') AS MAJ_CAT_NM,
        NVL(BM.SSN,'NA') AS SSN,
        CASE WHEN NVL(BM.SSN,'NA') IN ('S','PS') THEN 1.0 ELSE 0.5 END AS SF
    FROM MASTER_ST_MASTER SM
    CROSS JOIN MASTER_BIN_CAPACITY BC
    LEFT JOIN (
        SELECT SEG, DIV, SUB_DIV, MAJ_CAT_NM, SSN
        FROM MASTER_PRODUCT_HIERARCHY
        QUALIFY ROW_NUMBER() OVER (PARTITION BY MAJ_CAT_NM ORDER BY MAJ_CAT_NM) = 1
    ) BM ON BM.MAJ_CAT_NM = BC.MAJ_CAT
    WHERE (:STORE_CODE IS NULL OR SM.ST_CD = :STORE_CODE)
      AND (:MAJ_CAT_PARAM IS NULL OR BC.MAJ_CAT = :MAJ_CAT_PARAM);

    -- ═══ STEP 3: Filtered UNPIVOT (only relevant store/cat combos) ═══
    CREATE OR REPLACE TEMPORARY TABLE TMP_SQ AS
    SELECT ST_CD, MAJ_CAT, WK_NAME, SALE_QTY FROM (
        SELECT ST_CD, MAJ_CAT, {WK} FROM QTY_SALE_QTY
        WHERE (:STORE_CODE IS NULL OR ST_CD = :STORE_CODE)
          AND (:MAJ_CAT_PARAM IS NULL OR MAJ_CAT = :MAJ_CAT_PARAM)
    ) UNPIVOT (SALE_QTY FOR WK_NAME IN ({WK}));

    CREATE OR REPLACE TEMPORARY TABLE TMP_DQ AS
    SELECT ST_CD, MAJ_CAT, WK_NAME, DISP_QTY FROM (
        SELECT ST_CD, MAJ_CAT, {WK} FROM QTY_DISP_QTY
        WHERE (:STORE_CODE IS NULL OR ST_CD = :STORE_CODE)
          AND (:MAJ_CAT_PARAM IS NULL OR MAJ_CAT = :MAJ_CAT_PARAM)
    ) UNPIVOT (DISP_QTY FOR WK_NAME IN ({WK}));

    CREATE OR REPLACE TEMPORARY TABLE TMP_LS AS
    SELECT ST_CD, MAJ_CAT, STK_QTY FROM (
        SELECT ST_CD, MAJ_CAT, STK_QTY,
            ROW_NUMBER() OVER (PARTITION BY ST_CD, MAJ_CAT ORDER BY DATE DESC) AS RN
        FROM QTY_ST_STK_Q
        WHERE (:STORE_CODE IS NULL OR ST_CD = :STORE_CODE)
          AND (:MAJ_CAT_PARAM IS NULL OR MAJ_CAT = :MAJ_CAT_PARAM)
    ) WHERE RN = 1;

    -- ═══ STEP 4: Base data for recursive CTE ═══
    CREATE OR REPLACE TEMPORARY TABLE TMP_B AS
    SELECT SC.ST_CD, SC.MAJ_CAT, W.SEQ, W.WEEK_ID, SC.SSN, SC.SF,
        NVL(DQ.DISP_QTY,0) + NVL(SQ1.SALE_QTY,0) AS MBQ,
        NVL(SQ0.SALE_QTY,0) AS SALE,
        NVL(LS.STK_QTY,0) AS INIT_STK
    FROM TMP_SC SC
    CROSS JOIN TMP_W W
    LEFT JOIN TMP_SQ SQ0 ON SQ0.ST_CD=SC.ST_CD AND SQ0.MAJ_CAT=SC.MAJ_CAT AND SQ0.WK_NAME=W.WK_COL
    LEFT JOIN TMP_W W1 ON W1.WEEK_SEQ = W.WEEK_SEQ+1
    LEFT JOIN TMP_SQ SQ1 ON SQ1.ST_CD=SC.ST_CD AND SQ1.MAJ_CAT=SC.MAJ_CAT AND SQ1.WK_NAME=W1.WK_COL
    LEFT JOIN TMP_DQ DQ ON DQ.ST_CD=SC.ST_CD AND DQ.MAJ_CAT=SC.MAJ_CAT AND DQ.WK_NAME=NVL(W1.WK_COL,W.WK_COL)
    LEFT JOIN TMP_LS LS ON LS.ST_CD=SC.ST_CD AND LS.MAJ_CAT=SC.MAJ_CAT;

    -- ═══ STEP 5: Delete old data ═══
    DELETE FROM TRF_IN_PLAN
    WHERE WEEK_ID BETWEEN :START_WEEK_ID AND :END_WEEK_ID
      AND (:STORE_CODE IS NULL OR ST_CD = :STORE_CODE)
      AND (:MAJ_CAT_PARAM IS NULL OR MAJ_CAT = :MAJ_CAT_PARAM);

    -- ═══ STEP 6: Recursive CTE chain → INSERT ═══
    INSERT INTO TRF_IN_PLAN (
        ST_CD, ST_NM, RDC_CD, RDC_NM, HUB_CD, HUB_NM, AREA,
        MAJ_CAT, SSN, WEEK_ID, WK_ST_DT, WK_END_DT, FY_YEAR, FY_WEEK,
        SEG, DIV, SUB_DIV, MAJ_CAT_NM,
        S_GRT_STK_Q, W_GRT_STK_Q, BGT_DISP_CL_Q, BGT_DISP_CL_OPT,
        CM1_SALE_COVER_DAY, CM2_SALE_COVER_DAY, COVER_SALE_QTY,
        BGT_ST_CL_MBQ, BGT_DISP_CL_OPT_MBQ,
        BGT_TTL_CF_OP_STK_Q, NT_ACT_Q, NET_BGT_CF_STK_Q,
        CM_BGT_SALE_Q, CM1_BGT_SALE_Q, CM2_BGT_SALE_Q,
        TRF_IN_STK_Q, TRF_IN_OPT_CNT, TRF_IN_OPT_MBQ, DC_MBQ,
        BGT_TTL_CF_CL_STK_Q, BGT_NT_ACT_Q, NET_ST_CL_STK_Q,
        ST_CL_EXCESS_Q, ST_CL_SHORT_Q
    )
    WITH RECURSIVE chain(ST_CD, MAJ_CAT, SEQ, MBQ, SALE, OP_STK, NET_CF, TRF_IN, CL_STK) AS (
        -- ── Week 1: anchor ──
        SELECT ST_CD, MAJ_CAT, SEQ, MBQ, SALE,
            INIT_STK,
            GREATEST(INIT_STK - ROUND(ROUND(INIT_STK*0.08,0)*SF,0), 0),
            CASE WHEN MBQ=0 AND SALE=0 THEN 0
                 WHEN MBQ+SALE - GREATEST(INIT_STK - ROUND(ROUND(INIT_STK*0.08,0)*SF,0),0) > 0
                 THEN MBQ+SALE - GREATEST(INIT_STK - ROUND(ROUND(INIT_STK*0.08,0)*SF,0),0)
                 ELSE 0 END,
            CASE WHEN MBQ=0 AND SALE=0 THEN GREATEST(INIT_STK - ROUND(ROUND(INIT_STK*0.08,0)*SF,0),0)
                 WHEN MBQ+SALE > GREATEST(INIT_STK - ROUND(ROUND(INIT_STK*0.08,0)*SF,0),0) THEN MBQ
                 ELSE GREATEST(GREATEST(INIT_STK - ROUND(ROUND(INIT_STK*0.08,0)*SF,0),0) - SALE, 0) END
        FROM TMP_B WHERE SEQ = 1
        UNION ALL
        -- ── Week N: recursive ──
        SELECT n.ST_CD, n.MAJ_CAT, n.SEQ, n.MBQ, n.SALE,
            p.CL_STK,
            GREATEST(p.CL_STK - ROUND(ROUND(p.CL_STK*0.08,0)*n.SF,0), 0),
            CASE WHEN n.MBQ=0 AND n.SALE=0 THEN 0
                 WHEN n.MBQ+n.SALE - GREATEST(p.CL_STK - ROUND(ROUND(p.CL_STK*0.08,0)*n.SF,0),0) > 0
                 THEN n.MBQ+n.SALE - GREATEST(p.CL_STK - ROUND(ROUND(p.CL_STK*0.08,0)*n.SF,0),0)
                 ELSE 0 END,
            CASE WHEN n.MBQ=0 AND n.SALE=0 THEN GREATEST(p.CL_STK - ROUND(ROUND(p.CL_STK*0.08,0)*n.SF,0),0)
                 WHEN n.MBQ+n.SALE > GREATEST(p.CL_STK - ROUND(ROUND(p.CL_STK*0.08,0)*n.SF,0),0) THEN n.MBQ
                 ELSE GREATEST(GREATEST(p.CL_STK - ROUND(ROUND(p.CL_STK*0.08,0)*n.SF,0),0) - n.SALE, 0) END
        FROM TMP_B n
        INNER JOIN chain p ON p.ST_CD=n.ST_CD AND p.MAJ_CAT=n.MAJ_CAT AND n.SEQ=p.SEQ+1
    )
    SELECT
        SC.ST_CD, SC.ST_NM, SC.RDC_CD, SC.RDC_NM, SC.HUB_CD, SC.HUB_NM, SC.AREA,
        SC.MAJ_CAT, SC.SSN, W.WEEK_ID, W.WK_ST_DT, W.WK_END_DT, W.FY_YEAR, W.FY_WEEK,
        SC.SEG, SC.DIV, SC.SUB_DIV, SC.MAJ_CAT_NM,
        0,
        CASE WHEN SC.SSN IN ('W','PW') THEN CASE WHEN ch.SEQ=1 THEN 0 ELSE ch.OP_STK END ELSE 0 END,
        NVL(DQ.DISP_QTY,0),
        CASE WHEN SC.BIN_CAP>0 THEN ROUND(NVL(DQ.DISP_QTY,0)*1000.0/SC.BIN_CAP,0) ELSE 0 END,
        :COVER_DAYS_CM1, :COVER_DAYS_CM2,
        NVL(SQ1.SALE_QTY,0),
        ch.MBQ,
        CASE WHEN SC.BIN_CAP>0 AND ROUND(NVL(DQ.DISP_QTY,0)*1000.0/SC.BIN_CAP,0)>0
            THEN ROUND(ch.MBQ*1000.0/NULLIF(ROUND(NVL(DQ.DISP_QTY,0)*1000.0/SC.BIN_CAP,0),0),0) ELSE 0 END,
        ch.OP_STK,
        ROUND(ROUND(ch.OP_STK*0.08,0)*SC.SF,0),
        ch.NET_CF,
        ch.SALE,
        NVL(SQ1.SALE_QTY,0),
        NVL(SQ2.SALE_QTY,0),
        ch.TRF_IN, 0, 0,
        NVL(SQ1.SALE_QTY,0)+NVL(SQN2.SALE_QTY,0)+NVL(SQN3.SALE_QTY,0)+NVL(SQN4.SALE_QTY,0),
        ch.CL_STK, 0, ch.CL_STK,
        GREATEST(ch.CL_STK - ch.MBQ, 0),
        GREATEST(ch.MBQ - ch.CL_STK, 0)
    FROM chain ch
    INNER JOIN TMP_SC SC ON SC.ST_CD=ch.ST_CD AND SC.MAJ_CAT=ch.MAJ_CAT
    INNER JOIN TMP_W W ON W.SEQ=ch.SEQ
    LEFT JOIN TMP_W W1 ON W1.WEEK_SEQ=W.WEEK_SEQ+1
    LEFT JOIN TMP_SQ SQ1 ON SQ1.ST_CD=ch.ST_CD AND SQ1.MAJ_CAT=ch.MAJ_CAT AND SQ1.WK_NAME=W1.WK_COL
    LEFT JOIN TMP_W W2 ON W2.WEEK_SEQ=W.WEEK_SEQ+8
    LEFT JOIN TMP_SQ SQ2 ON SQ2.ST_CD=ch.ST_CD AND SQ2.MAJ_CAT=ch.MAJ_CAT AND SQ2.WK_NAME=W2.WK_COL
    LEFT JOIN TMP_W WN2 ON WN2.WEEK_SEQ=W.WEEK_SEQ+2
    LEFT JOIN TMP_SQ SQN2 ON SQN2.ST_CD=ch.ST_CD AND SQN2.MAJ_CAT=ch.MAJ_CAT AND SQN2.WK_NAME=WN2.WK_COL
    LEFT JOIN TMP_W WN3 ON WN3.WEEK_SEQ=W.WEEK_SEQ+3
    LEFT JOIN TMP_SQ SQN3 ON SQN3.ST_CD=ch.ST_CD AND SQN3.MAJ_CAT=ch.MAJ_CAT AND SQN3.WK_NAME=WN3.WK_COL
    LEFT JOIN TMP_W WN4 ON WN4.WEEK_SEQ=W.WEEK_SEQ+4
    LEFT JOIN TMP_SQ SQN4 ON SQN4.ST_CD=ch.ST_CD AND SQN4.MAJ_CAT=ch.MAJ_CAT AND SQN4.WK_NAME=WN4.WK_COL
    LEFT JOIN TMP_DQ DQ ON DQ.ST_CD=ch.ST_CD AND DQ.MAJ_CAT=ch.MAJ_CAT AND DQ.WK_NAME=NVL(W1.WK_COL,W.WK_COL);

    -- ═══ STEP 7: Post-update OPT columns ═══
    UPDATE TRF_IN_PLAN SET
        TRF_IN_OPT_CNT = CASE WHEN BGT_DISP_CL_OPT_MBQ>0 AND TRF_IN_STK_Q>0
            THEN ROUND(TRF_IN_STK_Q*1000.0/NULLIF(BGT_DISP_CL_OPT_MBQ,0),0) ELSE 0 END,
        TRF_IN_OPT_MBQ = CASE WHEN BGT_DISP_CL_OPT_MBQ>0 AND TRF_IN_STK_Q>0
            THEN NVL(TRF_IN_STK_Q*1000.0/NULLIF(ROUND(TRF_IN_STK_Q*1000.0/NULLIF(BGT_DISP_CL_OPT_MBQ,0),0),0),0) ELSE 0 END
    WHERE WEEK_ID BETWEEN :START_WEEK_ID AND :END_WEEK_ID
      AND (:STORE_CODE IS NULL OR ST_CD = :STORE_CODE)
      AND (:MAJ_CAT_PARAM IS NULL OR MAJ_CAT = :MAJ_CAT_PARAM);

    -- Count
    v_rows := (SELECT COUNT(*) FROM TRF_IN_PLAN
        WHERE WEEK_ID BETWEEN :START_WEEK_ID AND :END_WEEK_ID
          AND (:STORE_CODE IS NULL OR ST_CD = :STORE_CODE)
          AND (:MAJ_CAT_PARAM IS NULL OR MAJ_CAT = :MAJ_CAT_PARAM));

    -- Cleanup
    DROP TABLE IF EXISTS TMP_W;
    DROP TABLE IF EXISTS TMP_SC;
    DROP TABLE IF EXISTS TMP_SQ;
    DROP TABLE IF EXISTS TMP_DQ;
    DROP TABLE IF EXISTS TMP_LS;
    DROP TABLE IF EXISTS TMP_B;

    RETURN OBJECT_CONSTRUCT(
        'rows_inserted', :v_rows,
        'start_week', :START_WEEK_ID,
        'end_week', :END_WEEK_ID,
        'seconds', DATEDIFF('second', :v_ts, CURRENT_TIMESTAMP())
    );
END;
"""

# ================================================================
# SP 2: SF_SP_RUN_ALL_PLANS (TRUNCATE + TRF + PP)
# ================================================================
sp_runall_sql = f"""
CREATE OR REPLACE PROCEDURE SF_SP_RUN_ALL_PLANS(
    START_WEEK_ID FLOAT, END_WEEK_ID FLOAT,
    MAJ_CAT_PARAM VARCHAR DEFAULT NULL,
    COVER_DAYS_CM1 FLOAT DEFAULT 14, COVER_DAYS_CM2 FLOAT DEFAULT 0
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS CALLER
AS
DECLARE
    v_trf INTEGER;
    v_pp  INTEGER;
    v_ts  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
BEGIN
    -- Truncate both output tables
    TRUNCATE TABLE IF EXISTS TRF_IN_PLAN;
    TRUNCATE TABLE IF EXISTS PURCHASE_PLAN;

    -- Generate TRF (all stores, optional MAJ_CAT filter)
    CALL SF_SP_GENERATE_TRF_IN_PLAN(:START_WEEK_ID, :END_WEEK_ID, NULL, :MAJ_CAT_PARAM, :COVER_DAYS_CM1, :COVER_DAYS_CM2);
    v_trf := (SELECT COUNT(*) FROM TRF_IN_PLAN);

    -- Generate Purchase Plan
    IF (:MAJ_CAT_PARAM IS NULL) THEN
        CALL SF_SP_GENERATE_PURCHASE_PLAN(:START_WEEK_ID, :END_WEEK_ID, NULL, NULL);
    ELSE
        CALL SF_SP_GENERATE_PURCHASE_PLAN(:START_WEEK_ID, :END_WEEK_ID, NULL, :MAJ_CAT_PARAM);
    END IF;
    v_pp := (SELECT COUNT(*) FROM PURCHASE_PLAN);

    RETURN OBJECT_CONSTRUCT(
        'trf_rows', :v_trf,
        'pp_rows', :v_pp,
        'total_seconds', DATEDIFF('second', :v_ts, CURRENT_TIMESTAMP())
    );
END;
"""

# ================================================================
# DEPLOY
# ================================================================
print("Deploying SF_SP_GENERATE_TRF_IN_PLAN (SQL Scripting + Recursive CTE)...")
try:
    cur.execute(sp_trf_sql)
    print("  -> SF_SP_GENERATE_TRF_IN_PLAN deployed successfully.")
except Exception as e:
    print(f"  -> FAILED: {e}")
    sys.exit(1)

print("Deploying SF_SP_RUN_ALL_PLANS (SQL Scripting)...")
try:
    cur.execute(sp_runall_sql)
    print("  -> SF_SP_RUN_ALL_PLANS deployed successfully.")
except Exception as e:
    print(f"  -> FAILED: {e}")
    sys.exit(1)

print("\nBoth stored procedures deployed to V2RETAIL.GOLD")
print("  CALL SF_SP_GENERATE_TRF_IN_PLAN(1, 52, 'HJ08', NULL, 14, 0);")
print("  CALL SF_SP_RUN_ALL_PLANS(1, 52, NULL, 14, 0);")

conn.close()
