-- ============================================================
-- Create 4 Contribution Tables
-- ============================================================

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ST_MAJ_CAT_MACRO_MVGR_PLAN')
CREATE TABLE [dbo].[ST_MAJ_CAT_MACRO_MVGR_PLAN] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [ST_CD] NVARCHAR(50) NOT NULL DEFAULT 'NA',
    [MAJ_CAT_CD] NVARCHAR(100) NOT NULL DEFAULT 'NA',
    [DISP_MVGR_MATRIX] NVARCHAR(200) NOT NULL DEFAULT 'NA',
    [CONT_PCT] DECIMAL(18,4) NOT NULL DEFAULT 0
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ST_MAJ_CAT_SZ_PLAN')
CREATE TABLE [dbo].[ST_MAJ_CAT_SZ_PLAN] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [ST_CD] NVARCHAR(50) NOT NULL DEFAULT 'NA',
    [MAJ_CAT_CD] NVARCHAR(100) NOT NULL DEFAULT 'NA',
    [SZ] NVARCHAR(100) NOT NULL DEFAULT 'NA',
    [CONT_PCT] DECIMAL(18,4) NOT NULL DEFAULT 0
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ST_MAJ_CAT_SEG_PLAN')
CREATE TABLE [dbo].[ST_MAJ_CAT_SEG_PLAN] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [ST_CD] NVARCHAR(50) NOT NULL DEFAULT 'NA',
    [MAJ_CAT_CD] NVARCHAR(100) NOT NULL DEFAULT 'NA',
    [SEG] NVARCHAR(100) NOT NULL DEFAULT 'NA',
    [CONT_PCT] DECIMAL(18,4) NOT NULL DEFAULT 0
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ST_MAJ_CAT_VND_PLAN')
CREATE TABLE [dbo].[ST_MAJ_CAT_VND_PLAN] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [ST_CD] NVARCHAR(50) NOT NULL DEFAULT 'NA',
    [MAJ_CAT_CD] NVARCHAR(100) NOT NULL DEFAULT 'NA',
    [M_VND_CD] NVARCHAR(200) NOT NULL DEFAULT 'NA',
    [CONT_PCT] DECIMAL(18,4) NOT NULL DEFAULT 0
);
GO
