-- ============================================================
-- Sub-Level Output Tables (materialized from main plan × contribution)
-- ============================================================

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SUB_LEVEL_TRF_PLAN')
CREATE TABLE [dbo].[SUB_LEVEL_TRF_PLAN] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [LEVEL] VARCHAR(10) NOT NULL,
    [SUB_VALUE] NVARCHAR(200) NOT NULL DEFAULT 'NA',
    [ST_CD] NVARCHAR(50) NOT NULL,
    [MAJ_CAT] NVARCHAR(100) NOT NULL,
    [CONT_PCT] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [FY_YEAR] INT,
    [FY_WEEK] INT,
    [BGT_DISP_CL_Q] DECIMAL(18,4) DEFAULT 0,
    [CM_BGT_SALE_Q] DECIMAL(18,4) DEFAULT 0,
    [CM1_BGT_SALE_Q] DECIMAL(18,4) DEFAULT 0,
    [CM2_BGT_SALE_Q] DECIMAL(18,4) DEFAULT 0,
    [COVER_SALE_QTY] DECIMAL(18,4) DEFAULT 0,
    [TRF_IN_STK_Q] DECIMAL(18,4) DEFAULT 0,
    [DC_MBQ] DECIMAL(18,4) DEFAULT 0,
    [BGT_TTL_CF_OP_STK_Q] DECIMAL(18,4) DEFAULT 0,
    [BGT_TTL_CF_CL_STK_Q] DECIMAL(18,4) DEFAULT 0,
    [BGT_ST_CL_MBQ] DECIMAL(18,4) DEFAULT 0,
    [ST_CL_EXCESS_Q] DECIMAL(18,4) DEFAULT 0,
    [ST_CL_SHORT_Q] DECIMAL(18,4) DEFAULT 0,
    [CREATED_DT] DATETIME DEFAULT GETDATE()
);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SUB_LEVEL_PP_PLAN')
CREATE TABLE [dbo].[SUB_LEVEL_PP_PLAN] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [LEVEL] VARCHAR(10) NOT NULL,
    [SUB_VALUE] NVARCHAR(200) NOT NULL DEFAULT 'NA',
    [RDC_CD] NVARCHAR(50) NOT NULL,
    [MAJ_CAT] NVARCHAR(100) NOT NULL,
    [CONT_PCT] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [FY_YEAR] INT,
    [FY_WEEK] INT,
    [BGT_DISP_CL_Q] DECIMAL(18,4) DEFAULT 0,
    [CW_BGT_SALE_Q] DECIMAL(18,4) DEFAULT 0,
    [CW1_BGT_SALE_Q] DECIMAL(18,4) DEFAULT 0,
    [CW2_BGT_SALE_Q] DECIMAL(18,4) DEFAULT 0,
    [CW3_BGT_SALE_Q] DECIMAL(18,4) DEFAULT 0,
    [CW4_BGT_SALE_Q] DECIMAL(18,4) DEFAULT 0,
    [BGT_PUR_Q_INIT] DECIMAL(18,4) DEFAULT 0,
    [BGT_DC_CL_STK_Q] DECIMAL(18,4) DEFAULT 0,
    [BGT_DC_CL_MBQ] DECIMAL(18,4) DEFAULT 0,
    [BGT_DC_MBQ_SALE] DECIMAL(18,4) DEFAULT 0,
    [DC_STK_EXCESS_Q] DECIMAL(18,4) DEFAULT 0,
    [DC_STK_SHORT_Q] DECIMAL(18,4) DEFAULT 0,
    [CREATED_DT] DATETIME DEFAULT GETDATE()
);
GO

-- Indexes for fast filtering
CREATE NONCLUSTERED INDEX IX_SUB_TRF_LEVEL ON [dbo].[SUB_LEVEL_TRF_PLAN]([LEVEL],[ST_CD],[MAJ_CAT],[FY_WEEK]);
CREATE NONCLUSTERED INDEX IX_SUB_PP_LEVEL ON [dbo].[SUB_LEVEL_PP_PLAN]([LEVEL],[RDC_CD],[MAJ_CAT],[FY_WEEK]);
GO
