-- ============================================================
-- 8 Separate Sub-Level Stock Tables (4 Store + 4 DC)
-- ============================================================

-- Drop old single tables if they exist
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SUB_ST_STK_Q') DROP TABLE [dbo].[SUB_ST_STK_Q];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SUB_DC_STK_Q') DROP TABLE [dbo].[SUB_DC_STK_Q];
GO

-- ── Store Stock per level ────────────────────────────────────

CREATE TABLE [dbo].[SUB_ST_STK_MVGR] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [ST_CD] NVARCHAR(50) NOT NULL DEFAULT 'NA',
    [MAJ_CAT] NVARCHAR(100) NOT NULL DEFAULT 'NA',
    [SUB_VALUE] NVARCHAR(200) NOT NULL DEFAULT 'NA',
    [STK_QTY] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [DATE] DATETIME NULL
);
GO

CREATE TABLE [dbo].[SUB_ST_STK_SZ] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [ST_CD] NVARCHAR(50) NOT NULL DEFAULT 'NA',
    [MAJ_CAT] NVARCHAR(100) NOT NULL DEFAULT 'NA',
    [SUB_VALUE] NVARCHAR(200) NOT NULL DEFAULT 'NA',
    [STK_QTY] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [DATE] DATETIME NULL
);
GO

CREATE TABLE [dbo].[SUB_ST_STK_SEG] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [ST_CD] NVARCHAR(50) NOT NULL DEFAULT 'NA',
    [MAJ_CAT] NVARCHAR(100) NOT NULL DEFAULT 'NA',
    [SUB_VALUE] NVARCHAR(200) NOT NULL DEFAULT 'NA',
    [STK_QTY] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [DATE] DATETIME NULL
);
GO

CREATE TABLE [dbo].[SUB_ST_STK_VND] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [ST_CD] NVARCHAR(50) NOT NULL DEFAULT 'NA',
    [MAJ_CAT] NVARCHAR(100) NOT NULL DEFAULT 'NA',
    [SUB_VALUE] NVARCHAR(200) NOT NULL DEFAULT 'NA',
    [STK_QTY] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [DATE] DATETIME NULL
);
GO

-- ── DC Stock per level ───────────────────────────────────────

CREATE TABLE [dbo].[SUB_DC_STK_MVGR] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [RDC_CD] NVARCHAR(50) NOT NULL DEFAULT 'NA',
    [MAJ_CAT] NVARCHAR(100) NOT NULL DEFAULT 'NA',
    [SUB_VALUE] NVARCHAR(200) NOT NULL DEFAULT 'NA',
    [DC_STK_Q] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [GRT_STK_Q] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [W_GRT_STK_Q] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [DATE] DATETIME NULL
);
GO

CREATE TABLE [dbo].[SUB_DC_STK_SZ] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [RDC_CD] NVARCHAR(50) NOT NULL DEFAULT 'NA',
    [MAJ_CAT] NVARCHAR(100) NOT NULL DEFAULT 'NA',
    [SUB_VALUE] NVARCHAR(200) NOT NULL DEFAULT 'NA',
    [DC_STK_Q] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [GRT_STK_Q] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [W_GRT_STK_Q] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [DATE] DATETIME NULL
);
GO

CREATE TABLE [dbo].[SUB_DC_STK_SEG] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [RDC_CD] NVARCHAR(50) NOT NULL DEFAULT 'NA',
    [MAJ_CAT] NVARCHAR(100) NOT NULL DEFAULT 'NA',
    [SUB_VALUE] NVARCHAR(200) NOT NULL DEFAULT 'NA',
    [DC_STK_Q] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [GRT_STK_Q] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [W_GRT_STK_Q] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [DATE] DATETIME NULL
);
GO

CREATE TABLE [dbo].[SUB_DC_STK_VND] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,
    [RDC_CD] NVARCHAR(50) NOT NULL DEFAULT 'NA',
    [MAJ_CAT] NVARCHAR(100) NOT NULL DEFAULT 'NA',
    [SUB_VALUE] NVARCHAR(200) NOT NULL DEFAULT 'NA',
    [DC_STK_Q] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [GRT_STK_Q] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [W_GRT_STK_Q] DECIMAL(18,4) NOT NULL DEFAULT 0,
    [DATE] DATETIME NULL
);
GO

-- ── Indexes ──────────────────────────────────────────────────
CREATE NONCLUSTERED INDEX IX_SUB_ST_MVGR ON [dbo].[SUB_ST_STK_MVGR]([ST_CD],[MAJ_CAT]);
CREATE NONCLUSTERED INDEX IX_SUB_ST_SZ   ON [dbo].[SUB_ST_STK_SZ]([ST_CD],[MAJ_CAT]);
CREATE NONCLUSTERED INDEX IX_SUB_ST_SEG  ON [dbo].[SUB_ST_STK_SEG]([ST_CD],[MAJ_CAT]);
CREATE NONCLUSTERED INDEX IX_SUB_ST_VND  ON [dbo].[SUB_ST_STK_VND]([ST_CD],[MAJ_CAT]);
CREATE NONCLUSTERED INDEX IX_SUB_DC_MVGR ON [dbo].[SUB_DC_STK_MVGR]([RDC_CD],[MAJ_CAT]);
CREATE NONCLUSTERED INDEX IX_SUB_DC_SZ   ON [dbo].[SUB_DC_STK_SZ]([RDC_CD],[MAJ_CAT]);
CREATE NONCLUSTERED INDEX IX_SUB_DC_SEG  ON [dbo].[SUB_DC_STK_SEG]([RDC_CD],[MAJ_CAT]);
CREATE NONCLUSTERED INDEX IX_SUB_DC_VND  ON [dbo].[SUB_DC_STK_VND]([RDC_CD],[MAJ_CAT]);
GO
