-- =====================================================
-- TRANSFER IN PLAN Ã¢Â€Â” PIVOT DATA (Week-wise)
-- Run on 192.168.151.28 [planning]
-- =====================================================

USE [planning];
GO

-- =====================================================
-- QUERY 1: Full Pivot View (728 columns Ã¢Â€Â” all 14 metrics ÃƒÂ— 52 weeks)
-- Very wide Ã¢Â€Â” best viewed in Excel (right-click grid Ã¢Â†Â’ Save Results As CSV)
-- =====================================================
-- SELECT * FROM dbo.VW_TRF_IN_PIVOT ORDER BY [ST-CD], [MAJ-CAT];
-- GO

-- =====================================================
-- QUERY 2: TRF_IN_STK_Q (Transfer In Qty) Ã¢Â€Â” Pivoted by Week
-- Shows how much stock to transfer in per store ÃƒÂ— category ÃƒÂ— week
-- =====================================================
PRINT '=== TRANSFER IN QTY Ã¢Â€Â” WEEK WISE PIVOT ===';

SELECT
    ST_CD, ST_NM, RDC_CD, MAJ_CAT,
    MAX(CASE WHEN WEEK_ID = 1 THEN TRF_IN_STK_Q END) AS [W01],
    MAX(CASE WHEN WEEK_ID = 2 THEN TRF_IN_STK_Q END) AS [W02],
    MAX(CASE WHEN WEEK_ID = 3 THEN TRF_IN_STK_Q END) AS [W03],
    MAX(CASE WHEN WEEK_ID = 4 THEN TRF_IN_STK_Q END) AS [W04],
    MAX(CASE WHEN WEEK_ID = 5 THEN TRF_IN_STK_Q END) AS [W05],
    MAX(CASE WHEN WEEK_ID = 6 THEN TRF_IN_STK_Q END) AS [W06],
    MAX(CASE WHEN WEEK_ID = 7 THEN TRF_IN_STK_Q END) AS [W07],
    MAX(CASE WHEN WEEK_ID = 8 THEN TRF_IN_STK_Q END) AS [W08],
    MAX(CASE WHEN WEEK_ID = 9 THEN TRF_IN_STK_Q END) AS [W09],
    MAX(CASE WHEN WEEK_ID = 10 THEN TRF_IN_STK_Q END) AS [W10],
    MAX(CASE WHEN WEEK_ID = 11 THEN TRF_IN_STK_Q END) AS [W11],
    MAX(CASE WHEN WEEK_ID = 12 THEN TRF_IN_STK_Q END) AS [W12],
    MAX(CASE WHEN WEEK_ID = 13 THEN TRF_IN_STK_Q END) AS [W13],
    MAX(CASE WHEN WEEK_ID = 14 THEN TRF_IN_STK_Q END) AS [W14],
    MAX(CASE WHEN WEEK_ID = 15 THEN TRF_IN_STK_Q END) AS [W15],
    MAX(CASE WHEN WEEK_ID = 16 THEN TRF_IN_STK_Q END) AS [W16],
    MAX(CASE WHEN WEEK_ID = 17 THEN TRF_IN_STK_Q END) AS [W17],
    MAX(CASE WHEN WEEK_ID = 18 THEN TRF_IN_STK_Q END) AS [W18],
    MAX(CASE WHEN WEEK_ID = 19 THEN TRF_IN_STK_Q END) AS [W19],
    MAX(CASE WHEN WEEK_ID = 20 THEN TRF_IN_STK_Q END) AS [W20],
    MAX(CASE WHEN WEEK_ID = 21 THEN TRF_IN_STK_Q END) AS [W21],
    MAX(CASE WHEN WEEK_ID = 22 THEN TRF_IN_STK_Q END) AS [W22],
    MAX(CASE WHEN WEEK_ID = 23 THEN TRF_IN_STK_Q END) AS [W23],
    MAX(CASE WHEN WEEK_ID = 24 THEN TRF_IN_STK_Q END) AS [W24],
    MAX(CASE WHEN WEEK_ID = 25 THEN TRF_IN_STK_Q END) AS [W25],
    MAX(CASE WHEN WEEK_ID = 26 THEN TRF_IN_STK_Q END) AS [W26],
    MAX(CASE WHEN WEEK_ID = 27 THEN TRF_IN_STK_Q END) AS [W27],
    MAX(CASE WHEN WEEK_ID = 28 THEN TRF_IN_STK_Q END) AS [W28],
    MAX(CASE WHEN WEEK_ID = 29 THEN TRF_IN_STK_Q END) AS [W29],
    MAX(CASE WHEN WEEK_ID = 30 THEN TRF_IN_STK_Q END) AS [W30],
    MAX(CASE WHEN WEEK_ID = 31 THEN TRF_IN_STK_Q END) AS [W31],
    MAX(CASE WHEN WEEK_ID = 32 THEN TRF_IN_STK_Q END) AS [W32],
    MAX(CASE WHEN WEEK_ID = 33 THEN TRF_IN_STK_Q END) AS [W33],
    MAX(CASE WHEN WEEK_ID = 34 THEN TRF_IN_STK_Q END) AS [W34],
    MAX(CASE WHEN WEEK_ID = 35 THEN TRF_IN_STK_Q END) AS [W35],
    MAX(CASE WHEN WEEK_ID = 36 THEN TRF_IN_STK_Q END) AS [W36],
    MAX(CASE WHEN WEEK_ID = 37 THEN TRF_IN_STK_Q END) AS [W37],
    MAX(CASE WHEN WEEK_ID = 38 THEN TRF_IN_STK_Q END) AS [W38],
    MAX(CASE WHEN WEEK_ID = 39 THEN TRF_IN_STK_Q END) AS [W39],
    MAX(CASE WHEN WEEK_ID = 40 THEN TRF_IN_STK_Q END) AS [W40],
    MAX(CASE WHEN WEEK_ID = 41 THEN TRF_IN_STK_Q END) AS [W41],
    MAX(CASE WHEN WEEK_ID = 42 THEN TRF_IN_STK_Q END) AS [W42],
    MAX(CASE WHEN WEEK_ID = 43 THEN TRF_IN_STK_Q END) AS [W43],
    MAX(CASE WHEN WEEK_ID = 44 THEN TRF_IN_STK_Q END) AS [W44],
    MAX(CASE WHEN WEEK_ID = 45 THEN TRF_IN_STK_Q END) AS [W45],
    MAX(CASE WHEN WEEK_ID = 46 THEN TRF_IN_STK_Q END) AS [W46],
    MAX(CASE WHEN WEEK_ID = 47 THEN TRF_IN_STK_Q END) AS [W47],
    MAX(CASE WHEN WEEK_ID = 48 THEN TRF_IN_STK_Q END) AS [W48],
    MAX(CASE WHEN WEEK_ID = 49 THEN TRF_IN_STK_Q END) AS [W49],
    MAX(CASE WHEN WEEK_ID = 50 THEN TRF_IN_STK_Q END) AS [W50],
    MAX(CASE WHEN WEEK_ID = 51 THEN TRF_IN_STK_Q END) AS [W51],
    MAX(CASE WHEN WEEK_ID = 52 THEN TRF_IN_STK_Q END) AS [W52]
FROM dbo.TRF_IN_PLAN
GROUP BY ST_CD, ST_NM, RDC_CD, MAJ_CAT
ORDER BY ST_CD, MAJ_CAT;

GO

-- =====================================================
-- QUERY 3: CM_BGT_SALE_Q (Budget Sale Qty) Ã¢Â€Â” Pivoted by Week
-- =====================================================
PRINT '';
PRINT '=== BUDGET SALE QTY Ã¢Â€Â” WEEK WISE PIVOT ===';

SELECT
    ST_CD, ST_NM, RDC_CD, MAJ_CAT,
    MAX(CASE WHEN WEEK_ID = 1 THEN CM_BGT_SALE_Q END) AS [W01],
    MAX(CASE WHEN WEEK_ID = 2 THEN CM_BGT_SALE_Q END) AS [W02],
    MAX(CASE WHEN WEEK_ID = 3 THEN CM_BGT_SALE_Q END) AS [W03],
    MAX(CASE WHEN WEEK_ID = 4 THEN CM_BGT_SALE_Q END) AS [W04],
    MAX(CASE WHEN WEEK_ID = 5 THEN CM_BGT_SALE_Q END) AS [W05],
    MAX(CASE WHEN WEEK_ID = 6 THEN CM_BGT_SALE_Q END) AS [W06],
    MAX(CASE WHEN WEEK_ID = 7 THEN CM_BGT_SALE_Q END) AS [W07],
    MAX(CASE WHEN WEEK_ID = 8 THEN CM_BGT_SALE_Q END) AS [W08],
    MAX(CASE WHEN WEEK_ID = 9 THEN CM_BGT_SALE_Q END) AS [W09],
    MAX(CASE WHEN WEEK_ID = 10 THEN CM_BGT_SALE_Q END) AS [W10],
    MAX(CASE WHEN WEEK_ID = 11 THEN CM_BGT_SALE_Q END) AS [W11],
    MAX(CASE WHEN WEEK_ID = 12 THEN CM_BGT_SALE_Q END) AS [W12],
    MAX(CASE WHEN WEEK_ID = 13 THEN CM_BGT_SALE_Q END) AS [W13],
    MAX(CASE WHEN WEEK_ID = 14 THEN CM_BGT_SALE_Q END) AS [W14],
    MAX(CASE WHEN WEEK_ID = 15 THEN CM_BGT_SALE_Q END) AS [W15],
    MAX(CASE WHEN WEEK_ID = 16 THEN CM_BGT_SALE_Q END) AS [W16],
    MAX(CASE WHEN WEEK_ID = 17 THEN CM_BGT_SALE_Q END) AS [W17],
    MAX(CASE WHEN WEEK_ID = 18 THEN CM_BGT_SALE_Q END) AS [W18],
    MAX(CASE WHEN WEEK_ID = 19 THEN CM_BGT_SALE_Q END) AS [W19],
    MAX(CASE WHEN WEEK_ID = 20 THEN CM_BGT_SALE_Q END) AS [W20],
    MAX(CASE WHEN WEEK_ID = 21 THEN CM_BGT_SALE_Q END) AS [W21],
    MAX(CASE WHEN WEEK_ID = 22 THEN CM_BGT_SALE_Q END) AS [W22],
    MAX(CASE WHEN WEEK_ID = 23 THEN CM_BGT_SALE_Q END) AS [W23],
    MAX(CASE WHEN WEEK_ID = 24 THEN CM_BGT_SALE_Q END) AS [W24],
    MAX(CASE WHEN WEEK_ID = 25 THEN CM_BGT_SALE_Q END) AS [W25],
    MAX(CASE WHEN WEEK_ID = 26 THEN CM_BGT_SALE_Q END) AS [W26],
    MAX(CASE WHEN WEEK_ID = 27 THEN CM_BGT_SALE_Q END) AS [W27],
    MAX(CASE WHEN WEEK_ID = 28 THEN CM_BGT_SALE_Q END) AS [W28],
    MAX(CASE WHEN WEEK_ID = 29 THEN CM_BGT_SALE_Q END) AS [W29],
    MAX(CASE WHEN WEEK_ID = 30 THEN CM_BGT_SALE_Q END) AS [W30],
    MAX(CASE WHEN WEEK_ID = 31 THEN CM_BGT_SALE_Q END) AS [W31],
    MAX(CASE WHEN WEEK_ID = 32 THEN CM_BGT_SALE_Q END) AS [W32],
    MAX(CASE WHEN WEEK_ID = 33 THEN CM_BGT_SALE_Q END) AS [W33],
    MAX(CASE WHEN WEEK_ID = 34 THEN CM_BGT_SALE_Q END) AS [W34],
    MAX(CASE WHEN WEEK_ID = 35 THEN CM_BGT_SALE_Q END) AS [W35],
    MAX(CASE WHEN WEEK_ID = 36 THEN CM_BGT_SALE_Q END) AS [W36],
    MAX(CASE WHEN WEEK_ID = 37 THEN CM_BGT_SALE_Q END) AS [W37],
    MAX(CASE WHEN WEEK_ID = 38 THEN CM_BGT_SALE_Q END) AS [W38],
    MAX(CASE WHEN WEEK_ID = 39 THEN CM_BGT_SALE_Q END) AS [W39],
    MAX(CASE WHEN WEEK_ID = 40 THEN CM_BGT_SALE_Q END) AS [W40],
    MAX(CASE WHEN WEEK_ID = 41 THEN CM_BGT_SALE_Q END) AS [W41],
    MAX(CASE WHEN WEEK_ID = 42 THEN CM_BGT_SALE_Q END) AS [W42],
    MAX(CASE WHEN WEEK_ID = 43 THEN CM_BGT_SALE_Q END) AS [W43],
    MAX(CASE WHEN WEEK_ID = 44 THEN CM_BGT_SALE_Q END) AS [W44],
    MAX(CASE WHEN WEEK_ID = 45 THEN CM_BGT_SALE_Q END) AS [W45],
    MAX(CASE WHEN WEEK_ID = 46 THEN CM_BGT_SALE_Q END) AS [W46],
    MAX(CASE WHEN WEEK_ID = 47 THEN CM_BGT_SALE_Q END) AS [W47],
    MAX(CASE WHEN WEEK_ID = 48 THEN CM_BGT_SALE_Q END) AS [W48],
    MAX(CASE WHEN WEEK_ID = 49 THEN CM_BGT_SALE_Q END) AS [W49],
    MAX(CASE WHEN WEEK_ID = 50 THEN CM_BGT_SALE_Q END) AS [W50],
    MAX(CASE WHEN WEEK_ID = 51 THEN CM_BGT_SALE_Q END) AS [W51],
    MAX(CASE WHEN WEEK_ID = 52 THEN CM_BGT_SALE_Q END) AS [W52]
FROM dbo.TRF_IN_PLAN
GROUP BY ST_CD, ST_NM, RDC_CD, MAJ_CAT
ORDER BY ST_CD, MAJ_CAT;

GO

-- =====================================================
-- QUERY 4: ST_CL_SHORT_Q (Store Closing Short Qty) Ã¢Â€Â” Pivoted by Week
-- =====================================================
PRINT '';
PRINT '=== STORE SHORT QTY Ã¢Â€Â” WEEK WISE PIVOT ===';

SELECT
    ST_CD, ST_NM, RDC_CD, MAJ_CAT,
    MAX(CASE WHEN WEEK_ID = 1 THEN ST_CL_SHORT_Q END) AS [W01],
    MAX(CASE WHEN WEEK_ID = 2 THEN ST_CL_SHORT_Q END) AS [W02],
    MAX(CASE WHEN WEEK_ID = 3 THEN ST_CL_SHORT_Q END) AS [W03],
    MAX(CASE WHEN WEEK_ID = 4 THEN ST_CL_SHORT_Q END) AS [W04],
    MAX(CASE WHEN WEEK_ID = 5 THEN ST_CL_SHORT_Q END) AS [W05],
    MAX(CASE WHEN WEEK_ID = 6 THEN ST_CL_SHORT_Q END) AS [W06],
    MAX(CASE WHEN WEEK_ID = 7 THEN ST_CL_SHORT_Q END) AS [W07],
    MAX(CASE WHEN WEEK_ID = 8 THEN ST_CL_SHORT_Q END) AS [W08],
    MAX(CASE WHEN WEEK_ID = 9 THEN ST_CL_SHORT_Q END) AS [W09],
    MAX(CASE WHEN WEEK_ID = 10 THEN ST_CL_SHORT_Q END) AS [W10],
    MAX(CASE WHEN WEEK_ID = 11 THEN ST_CL_SHORT_Q END) AS [W11],
    MAX(CASE WHEN WEEK_ID = 12 THEN ST_CL_SHORT_Q END) AS [W12],
    MAX(CASE WHEN WEEK_ID = 13 THEN ST_CL_SHORT_Q END) AS [W13],
    MAX(CASE WHEN WEEK_ID = 14 THEN ST_CL_SHORT_Q END) AS [W14],
    MAX(CASE WHEN WEEK_ID = 15 THEN ST_CL_SHORT_Q END) AS [W15],
    MAX(CASE WHEN WEEK_ID = 16 THEN ST_CL_SHORT_Q END) AS [W16],
    MAX(CASE WHEN WEEK_ID = 17 THEN ST_CL_SHORT_Q END) AS [W17],
    MAX(CASE WHEN WEEK_ID = 18 THEN ST_CL_SHORT_Q END) AS [W18],
    MAX(CASE WHEN WEEK_ID = 19 THEN ST_CL_SHORT_Q END) AS [W19],
    MAX(CASE WHEN WEEK_ID = 20 THEN ST_CL_SHORT_Q END) AS [W20],
    MAX(CASE WHEN WEEK_ID = 21 THEN ST_CL_SHORT_Q END) AS [W21],
    MAX(CASE WHEN WEEK_ID = 22 THEN ST_CL_SHORT_Q END) AS [W22],
    MAX(CASE WHEN WEEK_ID = 23 THEN ST_CL_SHORT_Q END) AS [W23],
    MAX(CASE WHEN WEEK_ID = 24 THEN ST_CL_SHORT_Q END) AS [W24],
    MAX(CASE WHEN WEEK_ID = 25 THEN ST_CL_SHORT_Q END) AS [W25],
    MAX(CASE WHEN WEEK_ID = 26 THEN ST_CL_SHORT_Q END) AS [W26],
    MAX(CASE WHEN WEEK_ID = 27 THEN ST_CL_SHORT_Q END) AS [W27],
    MAX(CASE WHEN WEEK_ID = 28 THEN ST_CL_SHORT_Q END) AS [W28],
    MAX(CASE WHEN WEEK_ID = 29 THEN ST_CL_SHORT_Q END) AS [W29],
    MAX(CASE WHEN WEEK_ID = 30 THEN ST_CL_SHORT_Q END) AS [W30],
    MAX(CASE WHEN WEEK_ID = 31 THEN ST_CL_SHORT_Q END) AS [W31],
    MAX(CASE WHEN WEEK_ID = 32 THEN ST_CL_SHORT_Q END) AS [W32],
    MAX(CASE WHEN WEEK_ID = 33 THEN ST_CL_SHORT_Q END) AS [W33],
    MAX(CASE WHEN WEEK_ID = 34 THEN ST_CL_SHORT_Q END) AS [W34],
    MAX(CASE WHEN WEEK_ID = 35 THEN ST_CL_SHORT_Q END) AS [W35],
    MAX(CASE WHEN WEEK_ID = 36 THEN ST_CL_SHORT_Q END) AS [W36],
    MAX(CASE WHEN WEEK_ID = 37 THEN ST_CL_SHORT_Q END) AS [W37],
    MAX(CASE WHEN WEEK_ID = 38 THEN ST_CL_SHORT_Q END) AS [W38],
    MAX(CASE WHEN WEEK_ID = 39 THEN ST_CL_SHORT_Q END) AS [W39],
    MAX(CASE WHEN WEEK_ID = 40 THEN ST_CL_SHORT_Q END) AS [W40],
    MAX(CASE WHEN WEEK_ID = 41 THEN ST_CL_SHORT_Q END) AS [W41],
    MAX(CASE WHEN WEEK_ID = 42 THEN ST_CL_SHORT_Q END) AS [W42],
    MAX(CASE WHEN WEEK_ID = 43 THEN ST_CL_SHORT_Q END) AS [W43],
    MAX(CASE WHEN WEEK_ID = 44 THEN ST_CL_SHORT_Q END) AS [W44],
    MAX(CASE WHEN WEEK_ID = 45 THEN ST_CL_SHORT_Q END) AS [W45],
    MAX(CASE WHEN WEEK_ID = 46 THEN ST_CL_SHORT_Q END) AS [W46],
    MAX(CASE WHEN WEEK_ID = 47 THEN ST_CL_SHORT_Q END) AS [W47],
    MAX(CASE WHEN WEEK_ID = 48 THEN ST_CL_SHORT_Q END) AS [W48],
    MAX(CASE WHEN WEEK_ID = 49 THEN ST_CL_SHORT_Q END) AS [W49],
    MAX(CASE WHEN WEEK_ID = 50 THEN ST_CL_SHORT_Q END) AS [W50],
    MAX(CASE WHEN WEEK_ID = 51 THEN ST_CL_SHORT_Q END) AS [W51],
    MAX(CASE WHEN WEEK_ID = 52 THEN ST_CL_SHORT_Q END) AS [W52]
FROM dbo.TRF_IN_PLAN
GROUP BY ST_CD, ST_NM, RDC_CD, MAJ_CAT
ORDER BY ST_CD, MAJ_CAT;

GO

-- =====================================================
-- QUERY 5: BGT_TTL_CF_CL_STK_Q (Closing Stock) Ã¢Â€Â” Pivoted by Week
-- =====================================================
PRINT '';
PRINT '=== CLOSING STOCK QTY Ã¢Â€Â” WEEK WISE PIVOT ===';

SELECT
    ST_CD, ST_NM, RDC_CD, MAJ_CAT,
    MAX(CASE WHEN WEEK_ID = 1 THEN BGT_TTL_CF_CL_STK_Q END) AS [W01],
    MAX(CASE WHEN WEEK_ID = 2 THEN BGT_TTL_CF_CL_STK_Q END) AS [W02],
    MAX(CASE WHEN WEEK_ID = 3 THEN BGT_TTL_CF_CL_STK_Q END) AS [W03],
    MAX(CASE WHEN WEEK_ID = 4 THEN BGT_TTL_CF_CL_STK_Q END) AS [W04],
    MAX(CASE WHEN WEEK_ID = 5 THEN BGT_TTL_CF_CL_STK_Q END) AS [W05],
    MAX(CASE WHEN WEEK_ID = 6 THEN BGT_TTL_CF_CL_STK_Q END) AS [W06],
    MAX(CASE WHEN WEEK_ID = 7 THEN BGT_TTL_CF_CL_STK_Q END) AS [W07],
    MAX(CASE WHEN WEEK_ID = 8 THEN BGT_TTL_CF_CL_STK_Q END) AS [W08],
    MAX(CASE WHEN WEEK_ID = 9 THEN BGT_TTL_CF_CL_STK_Q END) AS [W09],
    MAX(CASE WHEN WEEK_ID = 10 THEN BGT_TTL_CF_CL_STK_Q END) AS [W10],
    MAX(CASE WHEN WEEK_ID = 11 THEN BGT_TTL_CF_CL_STK_Q END) AS [W11],
    MAX(CASE WHEN WEEK_ID = 12 THEN BGT_TTL_CF_CL_STK_Q END) AS [W12],
    MAX(CASE WHEN WEEK_ID = 13 THEN BGT_TTL_CF_CL_STK_Q END) AS [W13],
    MAX(CASE WHEN WEEK_ID = 14 THEN BGT_TTL_CF_CL_STK_Q END) AS [W14],
    MAX(CASE WHEN WEEK_ID = 15 THEN BGT_TTL_CF_CL_STK_Q END) AS [W15],
    MAX(CASE WHEN WEEK_ID = 16 THEN BGT_TTL_CF_CL_STK_Q END) AS [W16],
    MAX(CASE WHEN WEEK_ID = 17 THEN BGT_TTL_CF_CL_STK_Q END) AS [W17],
    MAX(CASE WHEN WEEK_ID = 18 THEN BGT_TTL_CF_CL_STK_Q END) AS [W18],
    MAX(CASE WHEN WEEK_ID = 19 THEN BGT_TTL_CF_CL_STK_Q END) AS [W19],
    MAX(CASE WHEN WEEK_ID = 20 THEN BGT_TTL_CF_CL_STK_Q END) AS [W20],
    MAX(CASE WHEN WEEK_ID = 21 THEN BGT_TTL_CF_CL_STK_Q END) AS [W21],
    MAX(CASE WHEN WEEK_ID = 22 THEN BGT_TTL_CF_CL_STK_Q END) AS [W22],
    MAX(CASE WHEN WEEK_ID = 23 THEN BGT_TTL_CF_CL_STK_Q END) AS [W23],
    MAX(CASE WHEN WEEK_ID = 24 THEN BGT_TTL_CF_CL_STK_Q END) AS [W24],
    MAX(CASE WHEN WEEK_ID = 25 THEN BGT_TTL_CF_CL_STK_Q END) AS [W25],
    MAX(CASE WHEN WEEK_ID = 26 THEN BGT_TTL_CF_CL_STK_Q END) AS [W26],
    MAX(CASE WHEN WEEK_ID = 27 THEN BGT_TTL_CF_CL_STK_Q END) AS [W27],
    MAX(CASE WHEN WEEK_ID = 28 THEN BGT_TTL_CF_CL_STK_Q END) AS [W28],
    MAX(CASE WHEN WEEK_ID = 29 THEN BGT_TTL_CF_CL_STK_Q END) AS [W29],
    MAX(CASE WHEN WEEK_ID = 30 THEN BGT_TTL_CF_CL_STK_Q END) AS [W30],
    MAX(CASE WHEN WEEK_ID = 31 THEN BGT_TTL_CF_CL_STK_Q END) AS [W31],
    MAX(CASE WHEN WEEK_ID = 32 THEN BGT_TTL_CF_CL_STK_Q END) AS [W32],
    MAX(CASE WHEN WEEK_ID = 33 THEN BGT_TTL_CF_CL_STK_Q END) AS [W33],
    MAX(CASE WHEN WEEK_ID = 34 THEN BGT_TTL_CF_CL_STK_Q END) AS [W34],
    MAX(CASE WHEN WEEK_ID = 35 THEN BGT_TTL_CF_CL_STK_Q END) AS [W35],
    MAX(CASE WHEN WEEK_ID = 36 THEN BGT_TTL_CF_CL_STK_Q END) AS [W36],
    MAX(CASE WHEN WEEK_ID = 37 THEN BGT_TTL_CF_CL_STK_Q END) AS [W37],
    MAX(CASE WHEN WEEK_ID = 38 THEN BGT_TTL_CF_CL_STK_Q END) AS [W38],
    MAX(CASE WHEN WEEK_ID = 39 THEN BGT_TTL_CF_CL_STK_Q END) AS [W39],
    MAX(CASE WHEN WEEK_ID = 40 THEN BGT_TTL_CF_CL_STK_Q END) AS [W40],
    MAX(CASE WHEN WEEK_ID = 41 THEN BGT_TTL_CF_CL_STK_Q END) AS [W41],
    MAX(CASE WHEN WEEK_ID = 42 THEN BGT_TTL_CF_CL_STK_Q END) AS [W42],
    MAX(CASE WHEN WEEK_ID = 43 THEN BGT_TTL_CF_CL_STK_Q END) AS [W43],
    MAX(CASE WHEN WEEK_ID = 44 THEN BGT_TTL_CF_CL_STK_Q END) AS [W44],
    MAX(CASE WHEN WEEK_ID = 45 THEN BGT_TTL_CF_CL_STK_Q END) AS [W45],
    MAX(CASE WHEN WEEK_ID = 46 THEN BGT_TTL_CF_CL_STK_Q END) AS [W46],
    MAX(CASE WHEN WEEK_ID = 47 THEN BGT_TTL_CF_CL_STK_Q END) AS [W47],
    MAX(CASE WHEN WEEK_ID = 48 THEN BGT_TTL_CF_CL_STK_Q END) AS [W48],
    MAX(CASE WHEN WEEK_ID = 49 THEN BGT_TTL_CF_CL_STK_Q END) AS [W49],
    MAX(CASE WHEN WEEK_ID = 50 THEN BGT_TTL_CF_CL_STK_Q END) AS [W50],
    MAX(CASE WHEN WEEK_ID = 51 THEN BGT_TTL_CF_CL_STK_Q END) AS [W51],
    MAX(CASE WHEN WEEK_ID = 52 THEN BGT_TTL_CF_CL_STK_Q END) AS [W52]
FROM dbo.TRF_IN_PLAN
GROUP BY ST_CD, ST_NM, RDC_CD, MAJ_CAT
ORDER BY ST_CD, MAJ_CAT;

GO

PRINT '';
PRINT 'TIP: To export full pivot view to Excel:';
PRINT '  1. Run: SELECT * FROM dbo.VW_TRF_IN_PIVOT ORDER BY [ST-CD], [MAJ-CAT]';
PRINT '  2. Right-click the results grid Ã¢Â†Â’ Save Results As Ã¢Â†Â’ CSV';
PRINT '  3. Open CSV in Excel';
GO
